# Generated by Django 4.2.7 on 2023-11-28 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Terrace', 'Terrace'), ('Bungalow', 'Bungalow'), ('Duplex', 'Duplex')], max_length=30)),
                ('status', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Lease', 'Lease')], max_length=100)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='property_images')),
                ('other_images', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('land_size', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
