# Generated by Django 4.2.7 on 2023-11-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1234567.0, max_digits=12),
            preserve_default=False,
        ),
    ]
